const loanFields = [
    { id: 101, extended: false, name: "0+", sysName: "Delinquency0Count" },
    { id: 102, extended: false, name: "30+", sysName: "Delinquency30Count" },
    { id: 103, extended: false, name: "60+", sysName: "Delinquency60Count" },
    { id: 104, extended: false, name: "90+", sysName: "Delinquency90Count" },
    {
        id: 105,
        extended: false,
        name: "Restr.",
        sysName: "DelinquencyRestructuringCount",
    },
    { id: 106, extended: false, name: "Status", sysName: "AccountRatingText" },
    {
        id: 107,
        extended: false,
        name: "Payment (CHB)",
        sysName: "calculatedBkiPayment",
    },
    { id: 108, extended: false, name: "Loan Type", sysName: "LoanTypeText" },
    { id: 109, extended: false, name: "Loan Amount", sysName: "LoanAmount" },
    {
        id: 110,
        extended: false,
        name: "Loan Currency",
        sysName: "LoanCurrencyCode",
    },
    {
        id: 111,
        extended: false,
        name: "Balance Amount",
        sysName: "CurrentBalanceAmount",
    },
    { id: 112, extended: false, name: "Debt Amount", sysName: "DebtAmount" },
    {
        id: 113,
        extended: false,
        name: "Unpaid Percent",
        sysName: "unpaidPercent",
    },
    {
        id: 114,
        extended: false,
        name: "Delinquency Amount",
        sysName: "DelinquencyAmount",
    },
    { id: 115, extended: false, name: "Guarantee", sysName: "AccountCodeText" },
    {
        id: 116,
        extended: false,
        name: "Creation Date",
        sysName: "LoanCreationDateText",
    },
    { id: 117, extended: false, name: "Close Date", sysName: "CloseDateText" },
    {
        id: 118,
        extended: false,
        name: "Last Update Date",
        sysName: "LastInfoUpdatedDateText",
    },
    {
        id: 119,
        extended: true,
        name: "Payment Period Count",
        sysName: "PaymentPeriodCount",
    },
    {
        id: 120,
        extended: true,
        name: "Months Number Since Date Of Creation",
        sysName: "monthsNumberSinceDateOfCreation",
    },
    {
        id: 121,
        extended: false,
        name: "Business Category",
        sysName: "BusinessCategory",
    },
    {
        id: 122,
        extended: false,
        name: "NBCH Loan Number",
        sysName: "nbkiLoanNumber",
    },
    {
        id: 123,
        extended: false,
        name: "OKB Loan Number",
        sysName: "okbLoanNumber",
    },
    {
        id: 124,
        extended: true,
        name: "Months Number Close Date Remaining",
        sysName: "monthsNumberCloseDateRemaining",
    },
    { id: 125, extended: true, name: "FLC Taken", sysName: "pskTaken" },
    { id: 126, extended: true, name: "FLC CBR", sysName: "pskCbr" },
    { id: 127, extended: true, name: "FLC NBCH", sysName: "pskNbki" },
    { id: 128, extended: true, name: "FLC OKB", sysName: "pskOkb" },
    {
        id: 129,
        extended: true,
        name: "Creditor Type (CBR-NBCH)",
        sysName: "creditorTypeNbki",
    },
    {
        id: 130,
        extended: true,
        name: "Creditor Type (CBR-OKB)",
        sysName: "creditorTypeOkb",
    },
    {
        id: 131,
        extended: true,
        name: "Loan Type (CBR-NBCH)",
        sysName: "loanTypeNbki",
    },
    {
        id: 132,
        extended: true,
        name: "Finance Type (CBR-OKB)",
        sysName: "financeTypeOkb",
    },
    {
        id: 133,
        extended: true,
        name: "Loan Type (CBR-OKB)",
        sysName: "financeTypeOkb",
    },
    {
        id: 134,
        extended: true,
        name: "Contract Period Count",
        sysName: "contractPeriodCount",
    },
    { id: 135, extended: false, name: "Payment (FLC)", sysName: "pskPayment" },
];

const paymentAmounts = [
    {
        id: 1,
        name: "Payments amount CHB: RUB",
        sysName: "bkiPaymentsAmountTotal",
        type: "CHB",
    },
    {
        id: 2,
        name: "RUB",
        sysName: "bkiPaymentsAmountRub",
        type: "CHB",
    },
    {
        id: 3,
        name: "USD",
        sysName: "bkiPaymentsAmountUsd",
        type: "CHB",
    },
    {
        id: 4,
        name: "EUR",
        sysName: "bkiPaymentsAmountEur",
        type: "CHB",
    },
    {
        id: 5,
        name: "Payments amount 4892-U: RUB",
        sysName: "pskPaymentsAmountTotal",
        type: "FLC",
    },
    {
        id: 6,
        name: "Loans amount: RUB",
        sysName: "bkiLoansAmount",
        type: "obligation",
    },
    {
        id: 7,
        name: "Cards amount: RUB",
        sysName: "bkiCreditCardsAmount",
        type: "obligation",
    },
];

const requestCounts = [
    { id: 1, name: "Total", sysName: "nbkiRequestsCount", type: "all" },
    {
        id: 2,
        name: "Last 24 months",
        sysName: "nbkiCollectionRequestCount",
        type: "all",
    },
    {
        id: 3,
        name: "Last 30 days",
        sysName: "nbkiLastRequestCount",
        type: "all",
    },
    {
        id: 4,
        sysName: "microcreditRequestsCount",
        name: "Total",
        type: "micro",
    },
    {
        id: 5,
        sysName: "last30DaysMicrocreditRequestsCount",
        name: "Last 30 days",
        type: "micro",
    },
    {
        id: 6,
        sysName: "lastYearMicrocreditRequestsCount",
        name: "Last year",
        type: "micro",
    },
    {
        id: 7,
        sysName: "more1YearMicrocreditRequestsCount",
        name: "More than 1 year",
        type: "micro",
    },
];

export { loanFields, paymentAmounts, requestCounts };
