const fields = [
    {
        id: 101,
        extended: false,
        name: "0+",
        sysName: "Delinquency0Count",
        type: "numeric",
    },
    {
        id: 102,
        extended: false,
        name: "30+",
        sysName: "Delinquency30Count",
        type: "numeric",
    },
    {
        id: 103,
        extended: false,
        name: "60+",
        sysName: "Delinquency60Count",
        type: "numeric",
    },
    {
        id: 104,
        extended: false,
        name: "90+",
        sysName: "Delinquency90Count",
        type: "numeric",
    },
    {
        id: 105,
        extended: false,
        name: "Restr.",
        sysName: "DelinquencyRestructuringCount",
        type: "numeric",
    },
    {
        id: 106,
        extended: false,
        name: "Status",
        sysName: "AccountRatingText",
        type: "text",
    },
    {
        id: 107,
        extended: false,
        name: "Payment (CHB)",
        sysName: "calculatedBkiPayment",
        sysNameStatus: "calculatedBkiStatus",
        type: "amount",
    },
    {
        id: 108,
        extended: false,
        name: "Loan Type",
        sysName: "LoanTypeText",
        type: "text",
    },
    {
        id: 109,
        extended: false,
        name: "Loan Amount",
        sysName: "LoanAmount",
        type: "amount",
    },
    {
        id: 110,
        extended: false,
        name: "Loan Currency",
        sysName: "LoanCurrencyCode",
        type: "text",
    },
    {
        id: 111,
        extended: false,
        name: "Balance Amount",
        sysName: "CurrentBalanceAmount",
        type: "amount",
    },
    {
        id: 112,
        extended: false,
        name: "Debt Amount",
        sysName: "DebtAmount",
        type: "amount",
    },
    {
        id: 113,
        extended: false,
        name: "Unpaid Percent",
        sysName: "unpaidPercent",
        sysNameStatus: "unpaidPercentStatus",
        type: "numeric",
    },
    {
        id: 114,
        extended: false,
        name: "Delinquency Amount",
        sysName: "DelinquencyAmount",
        type: "amount",
    },
    {
        id: 115,
        extended: false,
        name: "Guarantee",
        sysName: "AccountCodeText",
        type: "text",
    },
    {
        id: 116,
        extended: false,
        name: "Creation Date",
        sysName: "LoanCreationDate",
        type: "date",
    },
    {
        id: 117,
        extended: false,
        name: "Close Date",
        sysName: "CloseDate",
        type: "date",
    },
    {
        id: 118,
        extended: false,
        name: "Last Update Date",
        sysName: "LastInfoUpdatedDate",
        type: "date",
    },
    {
        id: 119,
        extended: true,
        name: "Payment Period Count",
        sysName: "PaymentPeriodCount",
        type: "numeric",
    },
    {
        id: 120,
        extended: true,
        name: "Months Number Since Date Of Creation",
        sysName: "monthsNumberSinceDateOfCreation",
        type: "numeric",
    },
    {
        id: 121,
        extended: false,
        name: "Business Category",
        sysName: "BusinessCategory",
        type: "text",
    },
    {
        id: 122,
        extended: false,
        name: "NBCH Loan Number",
        sysName: "nbkiLoanNumber",
        type: "numericArray",
    },
    {
        id: 123,
        extended: false,
        name: "OKB Loan Number",
        sysName: "okbLoanNumber",
        type: "numericArray",
    },
    {
        id: 124,
        extended: true,
        name: "Months Number Close Date Remaining",
        sysName: "monthsNumberCloseDateRemaining",
        type: "numeric",
    },
    {
        id: 125,
        extended: true,
        name: "FLC Taken",
        sysName: "pskTaken",
        type: "numeric",
    },
    {
        id: 126,
        extended: true,
        name: "FLC CBR",
        sysName: "pskCbr",
        type: "numeric",
    },
    {
        id: 127,
        extended: true,
        name: "FLC NBCH",
        sysName: "pskNbki",
        type: "numeric",
    },
    {
        id: 128,
        extended: true,
        name: "FLC OKB",
        sysName: "pskOkb",
        type: "numeric",
    },
    {
        id: 129,
        extended: true,
        name: "Creditor Type (CBR-NBCH)",
        sysName: "creditorTypeNbki",
        type: "text",
    },
    {
        id: 130,
        extended: true,
        name: "Creditor Type (CBR-OKB)",
        sysName: "creditorTypeOkb",
        type: "text",
    },
    {
        id: 131,
        extended: true,
        name: "Loan Type (CBR-NBCH)",
        sysName: "loanTypeNbki",
        type: "numeric",
    },
    {
        id: 132,
        extended: true,
        name: "Finance Type (CBR-OKB)",
        sysName: "financeTypeOkb",
        type: "numeric",
    },
    {
        id: 133,
        extended: true,
        name: "Loan Type (CBR-OKB)",
        sysName: "financeTypeOkb",
        type: "numeric",
    },
    {
        id: 134,
        extended: true,
        name: "Contract Period Count",
        sysName: "contractPeriodCount",
        type: "numeric",
    },
    {
        id: 135,
        extended: false,
        name: "Payment (FLC)",
        sysName: "pskPayment",
        sysNameStatus: "calculatedBkiStatus",
        type: "amount",
    },
];

const paymentAmounts = [
    {
        id: 1,
        name: "Payments amount CHB: RUB",
        sysName: "bkiPaymentsAmountTotal",
        type: "CHB",
    },
    {
        id: 2,
        name: "RUB",
        sysName: "bkiPaymentsAmountRub",
        type: "CHB",
    },
    {
        id: 3,
        name: "USD",
        sysName: "bkiPaymentsAmountUsd",
        type: "CHB",
    },
    {
        id: 4,
        name: "EUR",
        sysName: "bkiPaymentsAmountEur",
        type: "CHB",
    },
    {
        id: 5,
        name: "Payments amount FLC: RUB",
        sysName: "pskPaymentsAmountTotal",
        type: "FLC",
    },
    {
        id: 6,
        name: "Loans amount: RUB",
        sysName: "bkiLoansAmount",
        type: "obligation",
    },
    {
        id: 7,
        name: "Cards amount: RUB",
        sysName: "bkiCreditCardsAmount",
        type: "obligation",
    },
];

const requestCounts = [
    { id: 1, name: "Total", sysName: "nbkiRequestsCount", type: "all" },
    {
        id: 2,
        name: "Last 24 months",
        sysName: "nbkiCollectionRequestCount",
        type: "all",
    },
    {
        id: 3,
        name: "Last 30 days",
        sysName: "nbkiLastRequestCount",
        type: "all",
    },
    {
        id: 4,
        sysName: "microcreditRequestsCount",
        name: "Total",
        type: "micro",
    },
    {
        id: 5,
        sysName: "last30DaysMicrocreditRequestsCount",
        name: "Last 30 days",
        type: "micro",
    },
    {
        id: 6,
        sysName: "lastYearMicrocreditRequestsCount",
        name: "Last year",
        type: "micro",
    },
    {
        id: 7,
        sysName: "more1YearMicrocreditRequestsCount",
        name: "More than 1 year",
        type: "micro",
    },
];

export { fields, paymentAmounts, requestCounts };
